{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "[Errno 2] No such file or directory: 'uilogin.ui'", "severity": "ERROR", "timestamp": "2024-09-22T09:41:14Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "[Errno 2] No such file or directory: 'login.ui'", "severity": "ERROR", "timestamp": "2024-09-22T09:43:54Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "[Errno 2] No such file or directory: 'login.ui'", "severity": "ERROR", "timestamp": "2024-09-22T09:44:13Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "Error durante la consulta: 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ''123''' at line 1", "severity": "ERROR", "timestamp": "2024-09-27T12:26:40Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "Error durante la consulta: 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ''''' at line 1", "severity": "ERROR", "timestamp": "2024-09-27T12:26:53Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "Error durante la consulta: 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ''''' at line 1", "severity": "ERROR", "timestamp": "2024-09-27T12:26:53Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "Error durante la consulta: 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ''11''' at line 1", "severity": "ERROR", "timestamp": "2024-09-27T12:26:56Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "Error durante la consulta: 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ''11''' at line 1", "severity": "ERROR", "timestamp": "2024-09-27T12:26:56Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "Error durante la consulta: 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ''11''' at line 1", "severity": "ERROR", "timestamp": "2024-09-27T12:26:56Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "Error durante la consulta: 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ''123''' at line 1", "severity": "ERROR", "timestamp": "2024-09-27T12:28:03Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "obtener_usuario() takes 2 positional arguments but 3 were given", "severity": "ERROR", "timestamp": "2024-09-27T12:29:28Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "obtener_usuario() takes 2 positional arguments but 3 were given", "severity": "ERROR", "timestamp": "2024-09-27T12:30:54Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "'QLabel' object has no attribute 'set'", "severity": "ERROR", "timestamp": "2024-09-28T20:06:06Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "'QLabel' object has no attribute 'set'", "severity": "ERROR", "timestamp": "2024-09-28T20:06:49Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "'QLabel' object has no attribute 'set'", "severity": "ERROR", "timestamp": "2024-09-28T20:07:33Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "execute() missing 1 required positional argument: 'operation'", "severity": "ERROR", "timestamp": "2024-09-28T21:08:54Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "execute() missing 1 required positional argument: 'operation'", "severity": "ERROR", "timestamp": "2024-09-28T21:10:20Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "'Database' object has no attribute 'conneccion'", "severity": "ERROR", "timestamp": "2024-09-28T21:13:34Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "'Database' object has no attribute 'conneccion'", "severity": "ERROR", "timestamp": "2024-09-28T21:14:03Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "'Database' object has no attribute 'conneccion'", "severity": "ERROR", "timestamp": "2024-09-28T21:14:03Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "'Database' object has no attribute 'conneccion'", "severity": "ERROR", "timestamp": "2024-09-28T21:14:08Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "'Database' object has no attribute 'conneccion'", "severity": "ERROR", "timestamp": "2024-09-28T21:14:08Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "'Database' object has no attribute 'conneccion'", "severity": "ERROR", "timestamp": "2024-09-28T21:14:08Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "'Database' object has no attribute 'conneccion'", "severity": "ERROR", "timestamp": "2024-09-28T21:14:42Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "'Database' object has no attribute 'conneccion'", "severity": "ERROR", "timestamp": "2024-09-28T21:14:42Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "'Database' object has no attribute 'conneccion'", "severity": "ERROR", "timestamp": "2024-09-28T21:14:42Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "'Database' object has no attribute 'conneccion'", "severity": "ERROR", "timestamp": "2024-09-28T21:14:42Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "'Database' object has no attribute 'desconectar'", "severity": "ERROR", "timestamp": "2024-09-28T21:15:28Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "'NoneType' object is not subscriptable", "severity": "ERROR", "timestamp": "2024-09-28T21:23:57Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "'NoneType' object is not subscriptable", "severity": "ERROR", "timestamp": "2024-09-28T21:24:08Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "'NoneType' object is not subscriptable", "severity": "ERROR", "timestamp": "2024-09-28T21:24:08Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "'NoneType' object is not subscriptable", "severity": "ERROR", "timestamp": "2024-09-28T21:26:43Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "'NoneType' object is not subscriptable", "severity": "ERROR", "timestamp": "2024-09-28T21:28:46Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "'NoneType' object is not subscriptable", "severity": "ERROR", "timestamp": "2024-09-28T21:28:46Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "'NoneType' object is not subscriptable", "severity": "ERROR", "timestamp": "2024-09-28T21:30:14Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "'NoneType' object is not subscriptable", "severity": "ERROR", "timestamp": "2024-09-28T21:30:14Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "'NoneType' object is not subscriptable", "severity": "ERROR", "timestamp": "2024-09-28T21:30:14Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "'NoneType' object is not subscriptable", "severity": "ERROR", "timestamp": "2024-09-28T21:30:17Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "'NoneType' object is not subscriptable", "severity": "ERROR", "timestamp": "2024-09-28T21:30:17Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "'NoneType' object is not subscriptable", "severity": "ERROR", "timestamp": "2024-09-28T21:30:17Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "'NoneType' object is not subscriptable", "severity": "ERROR", "timestamp": "2024-09-28T21:30:17Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "'NoneType' object is not subscriptable", "severity": "ERROR", "timestamp": "2024-09-28T21:30:28Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "'NoneType' object is not subscriptable", "severity": "ERROR", "timestamp": "2024-09-28T21:36:06Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "'NoneType' object is not subscriptable", "severity": "ERROR", "timestamp": "2024-09-28T21:36:45Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "'NoneType' object is not subscriptable", "severity": "ERROR", "timestamp": "2024-09-28T21:36:45Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "Error al insertar usuario: Not enough parameters for the SQL statement", "severity": "ERROR", "timestamp": "2024-09-30T15:12:25Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "Error al insertar usuario: Not enough parameters for the SQL statement", "severity": "ERROR", "timestamp": "2024-09-30T15:14:16Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "'AgregarUsuario' object has no attribute 'txtNombreUsuario'", "severity": "ERROR", "timestamp": "2024-09-30T15:16:34Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "'QPushButton' object has no attribute 'connect'", "severity": "ERROR", "timestamp": "2024-09-30T15:57:19Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "1054 (42S22): Unknown column 'nombre' in 'where clause'", "severity": "ERROR", "timestamp": "2024-09-30T16:41:33Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "Error al eliminar usuario: 1054 (42S22): Unknown column 'nombre' in 'where clause'", "severity": "ERROR", "timestamp": "2024-09-30T16:41:33Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "Error al eliminar usuario: 1054 (42S22): Unknown column 'nombre' in 'where clause'", "severity": "ERROR", "timestamp": "2024-09-30T16:41:33Z"}
