{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "[Errno 2] No such file or directory: 'uilogin.ui'", "severity": "ERROR", "timestamp": "2024-09-22T09:41:14Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "[Errno 2] No such file or directory: 'login.ui'", "severity": "ERROR", "timestamp": "2024-09-22T09:43:54Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "[Errno 2] No such file or directory: 'login.ui'", "severity": "ERROR", "timestamp": "2024-09-22T09:44:13Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "Error durante la consulta: 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ''123''' at line 1", "severity": "ERROR", "timestamp": "2024-09-27T12:26:40Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "Error durante la consulta: 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ''''' at line 1", "severity": "ERROR", "timestamp": "2024-09-27T12:26:53Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "Error durante la consulta: 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ''''' at line 1", "severity": "ERROR", "timestamp": "2024-09-27T12:26:53Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "Error durante la consulta: 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ''11''' at line 1", "severity": "ERROR", "timestamp": "2024-09-27T12:26:56Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "Error durante la consulta: 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ''11''' at line 1", "severity": "ERROR", "timestamp": "2024-09-27T12:26:56Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "Error durante la consulta: 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ''11''' at line 1", "severity": "ERROR", "timestamp": "2024-09-27T12:26:56Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "Error durante la consulta: 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ''123''' at line 1", "severity": "ERROR", "timestamp": "2024-09-27T12:28:03Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "obtener_usuario() takes 2 positional arguments but 3 were given", "severity": "ERROR", "timestamp": "2024-09-27T12:29:28Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "obtener_usuario() takes 2 positional arguments but 3 were given", "severity": "ERROR", "timestamp": "2024-09-27T12:30:54Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "'QLabel' object has no attribute 'set'", "severity": "ERROR", "timestamp": "2024-09-28T20:06:06Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "'QLabel' object has no attribute 'set'", "severity": "ERROR", "timestamp": "2024-09-28T20:06:49Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "'QLabel' object has no attribute 'set'", "severity": "ERROR", "timestamp": "2024-09-28T20:07:33Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "execute() missing 1 required positional argument: 'operation'", "severity": "ERROR", "timestamp": "2024-09-28T21:08:54Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "execute() missing 1 required positional argument: 'operation'", "severity": "ERROR", "timestamp": "2024-09-28T21:10:20Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "'Database' object has no attribute 'conneccion'", "severity": "ERROR", "timestamp": "2024-09-28T21:13:34Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "'Database' object has no attribute 'conneccion'", "severity": "ERROR", "timestamp": "2024-09-28T21:14:03Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "'Database' object has no attribute 'conneccion'", "severity": "ERROR", "timestamp": "2024-09-28T21:14:03Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "'Database' object has no attribute 'conneccion'", "severity": "ERROR", "timestamp": "2024-09-28T21:14:08Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "'Database' object has no attribute 'conneccion'", "severity": "ERROR", "timestamp": "2024-09-28T21:14:08Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "'Database' object has no attribute 'conneccion'", "severity": "ERROR", "timestamp": "2024-09-28T21:14:08Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "'Database' object has no attribute 'conneccion'", "severity": "ERROR", "timestamp": "2024-09-28T21:14:42Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "'Database' object has no attribute 'conneccion'", "severity": "ERROR", "timestamp": "2024-09-28T21:14:42Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "'Database' object has no attribute 'conneccion'", "severity": "ERROR", "timestamp": "2024-09-28T21:14:42Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "'Database' object has no attribute 'conneccion'", "severity": "ERROR", "timestamp": "2024-09-28T21:14:42Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "'Database' object has no attribute 'desconectar'", "severity": "ERROR", "timestamp": "2024-09-28T21:15:28Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "'NoneType' object is not subscriptable", "severity": "ERROR", "timestamp": "2024-09-28T21:23:57Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "'NoneType' object is not subscriptable", "severity": "ERROR", "timestamp": "2024-09-28T21:24:08Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "'NoneType' object is not subscriptable", "severity": "ERROR", "timestamp": "2024-09-28T21:24:08Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "'NoneType' object is not subscriptable", "severity": "ERROR", "timestamp": "2024-09-28T21:26:43Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "'NoneType' object is not subscriptable", "severity": "ERROR", "timestamp": "2024-09-28T21:28:46Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "'NoneType' object is not subscriptable", "severity": "ERROR", "timestamp": "2024-09-28T21:28:46Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "'NoneType' object is not subscriptable", "severity": "ERROR", "timestamp": "2024-09-28T21:30:14Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "'NoneType' object is not subscriptable", "severity": "ERROR", "timestamp": "2024-09-28T21:30:14Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "'NoneType' object is not subscriptable", "severity": "ERROR", "timestamp": "2024-09-28T21:30:14Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "'NoneType' object is not subscriptable", "severity": "ERROR", "timestamp": "2024-09-28T21:30:17Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "'NoneType' object is not subscriptable", "severity": "ERROR", "timestamp": "2024-09-28T21:30:17Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "'NoneType' object is not subscriptable", "severity": "ERROR", "timestamp": "2024-09-28T21:30:17Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "'NoneType' object is not subscriptable", "severity": "ERROR", "timestamp": "2024-09-28T21:30:17Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "'NoneType' object is not subscriptable", "severity": "ERROR", "timestamp": "2024-09-28T21:30:28Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "'NoneType' object is not subscriptable", "severity": "ERROR", "timestamp": "2024-09-28T21:36:06Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "'NoneType' object is not subscriptable", "severity": "ERROR", "timestamp": "2024-09-28T21:36:45Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "'NoneType' object is not subscriptable", "severity": "ERROR", "timestamp": "2024-09-28T21:36:45Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "Error al insertar usuario: Not enough parameters for the SQL statement", "severity": "ERROR", "timestamp": "2024-09-30T15:12:25Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "Error al insertar usuario: Not enough parameters for the SQL statement", "severity": "ERROR", "timestamp": "2024-09-30T15:14:16Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "'AgregarUsuario' object has no attribute 'txtNombreUsuario'", "severity": "ERROR", "timestamp": "2024-09-30T15:16:34Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "'QPushButton' object has no attribute 'connect'", "severity": "ERROR", "timestamp": "2024-09-30T15:57:19Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "1054 (42S22): Unknown column 'nombre' in 'where clause'", "severity": "ERROR", "timestamp": "2024-09-30T16:41:33Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "Error al eliminar usuario: 1054 (42S22): Unknown column 'nombre' in 'where clause'", "severity": "ERROR", "timestamp": "2024-09-30T16:41:33Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "Error al eliminar usuario: 1054 (42S22): Unknown column 'nombre' in 'where clause'", "severity": "ERROR", "timestamp": "2024-09-30T16:41:33Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "'MySQLConnection' object has no attribute 'conneccion'", "severity": "ERROR", "timestamp": "2024-10-02T14:54:27Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "'MySQLConnection' object has no attribute 'desconeccion'", "severity": "ERROR", "timestamp": "2024-10-02T14:54:27Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "'MySQLConnection' object has no attribute 'desconeccion'", "severity": "ERROR", "timestamp": "2024-10-02T14:54:27Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "'MySQLConnection' object has no attribute 'conneccion'", "severity": "ERROR", "timestamp": "2024-10-02T14:55:31Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "'MySQLConnection' object has no attribute 'conneccion'", "severity": "ERROR", "timestamp": "2024-10-02T14:55:31Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "'MySQLConnection' object has no attribute 'conneccion'", "severity": "ERROR", "timestamp": "2024-10-02T14:55:31Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "'MySQLConnection' object has no attribute 'desconeccion'", "severity": "ERROR", "timestamp": "2024-10-02T14:55:31Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "'MySQLConnection' object has no attribute 'desconeccion'", "severity": "ERROR", "timestamp": "2024-10-02T14:55:31Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "'MySQLConnection' object has no attribute 'desconeccion'", "severity": "ERROR", "timestamp": "2024-10-02T14:55:31Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "'MySQLConnection' object has no attribute 'desconeccion'", "severity": "ERROR", "timestamp": "2024-10-02T14:55:31Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "'MySQLConnection' object has no attribute 'conneccion'", "severity": "ERROR", "timestamp": "2024-10-02T14:58:46Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "'MySQLConnection' object has no attribute 'desconeccion'", "severity": "ERROR", "timestamp": "2024-10-02T14:58:46Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "'MySQLConnection' object has no attribute 'desconeccion'", "severity": "ERROR", "timestamp": "2024-10-02T14:58:46Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "'MySQLConnection' object has no attribute 'conneccion'", "severity": "ERROR", "timestamp": "2024-10-02T15:03:35Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "'MySQLConnection' object has no attribute 'desconeccion'", "severity": "ERROR", "timestamp": "2024-10-02T15:03:35Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "'MySQLConnection' object has no attribute 'desconeccion'", "severity": "ERROR", "timestamp": "2024-10-02T15:03:35Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "'NoneType' object is not subscriptable", "severity": "ERROR", "timestamp": "2024-10-02T15:08:56Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "'NoneType' object is not subscriptable", "severity": "ERROR", "timestamp": "2024-10-02T15:09:00Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "'NoneType' object is not subscriptable", "severity": "ERROR", "timestamp": "2024-10-02T15:09:00Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "'NoneType' object is not subscriptable", "severity": "ERROR", "timestamp": "2024-10-02T15:10:41Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "obtener_usuario() missing 1 required positional argument: 'contrasena'", "severity": "ERROR", "timestamp": "2024-10-05T19:09:21Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "Could not process parameters: str(prueba), it must be of type list, tuple or dict", "severity": "ERROR", "timestamp": "2024-10-05T19:10:21Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "Error durante la consulta: Could not process parameters: str(prueba), it must be of type list, tuple or dict", "severity": "ERROR", "timestamp": "2024-10-05T19:10:21Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "Error durante la consulta: Could not process parameters: str(prueba), it must be of type list, tuple or dict", "severity": "ERROR", "timestamp": "2024-10-05T19:10:21Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "Could not process parameters: str(prueba), it must be of type list, tuple or dict", "severity": "ERROR", "timestamp": "2024-10-05T19:10:28Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "Could not process parameters: str(prueba), it must be of type list, tuple or dict", "severity": "ERROR", "timestamp": "2024-10-05T19:10:28Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "Could not process parameters: str(prueba), it must be of type list, tuple or dict", "severity": "ERROR", "timestamp": "2024-10-05T19:10:28Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "Error durante la consulta: Could not process parameters: str(prueba), it must be of type list, tuple or dict", "severity": "ERROR", "timestamp": "2024-10-05T19:10:28Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "Error durante la consulta: Could not process parameters: str(prueba), it must be of type list, tuple or dict", "severity": "ERROR", "timestamp": "2024-10-05T19:10:28Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "Error durante la consulta: Could not process parameters: str(prueba), it must be of type list, tuple or dict", "severity": "ERROR", "timestamp": "2024-10-05T19:10:28Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "Error durante la consulta: Could not process parameters: str(prueba), it must be of type list, tuple or dict", "severity": "ERROR", "timestamp": "2024-10-05T19:10:28Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "non-hexadecimal number found in fromhex() arg at position 0", "severity": "ERROR", "timestamp": "2024-10-05T19:11:58Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "non-hexadecimal number found in fromhex() arg at position 0", "severity": "ERROR", "timestamp": "2024-10-05T19:12:16Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "non-hexadecimal number found in fromhex() arg at position 0", "severity": "ERROR", "timestamp": "2024-10-05T19:12:16Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "non-hexadecimal number found in fromhex() arg at position 0", "severity": "ERROR", "timestamp": "2024-10-05T19:13:12Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "'MainWindow' object has no attribute 'tablapelis'", "severity": "ERROR", "timestamp": "2024-10-06T18:52:44Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "'MainWindow' object has no attribute 'tablapelis'", "severity": "ERROR", "timestamp": "2024-10-06T18:59:14Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "'MainWindow' object has no attribute 'tablapelis'", "severity": "ERROR", "timestamp": "2024-10-06T19:03:49Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "'AgregarPeliculas' object has no attribute 'ruta_imagen'", "severity": "ERROR", "timestamp": "2024-10-08T20:46:20Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "insertar_pelicula() missing 1 required positional argument: 'fecha_fin'", "severity": "ERROR", "timestamp": "2024-10-08T20:51:17Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "1054 (42S22): Unknown column 'nombre' in 'field list'", "severity": "ERROR", "timestamp": "2024-10-08T20:53:06Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "Error al insertar pel\u00edcula: 1054 (42S22): Unknown column 'nombre' in 'field list'", "severity": "ERROR", "timestamp": "2024-10-08T20:53:06Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "Error al insertar pel\u00edcula: 1054 (42S22): Unknown column 'nombre' in 'field list'", "severity": "ERROR", "timestamp": "2024-10-08T20:53:06Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "1136 (21S01): Column count doesn't match value count at row 1", "severity": "ERROR", "timestamp": "2024-10-08T20:56:26Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "Error al insertar pel\u00edcula: 1136 (21S01): Column count doesn't match value count at row 1", "severity": "ERROR", "timestamp": "2024-10-08T20:56:26Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "Error al insertar pel\u00edcula: 1136 (21S01): Column count doesn't match value count at row 1", "severity": "ERROR", "timestamp": "2024-10-08T20:56:26Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "'method' object is not iterable", "severity": "ERROR", "timestamp": "2024-10-11T16:44:09Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "1054 (42S22): Unknown column 'IdPeliculas' in 'where clause'", "severity": "ERROR", "timestamp": "2024-10-11T16:46:06Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "Error al eliminar pel\u00edcula: 1054 (42S22): Unknown column 'IdPeliculas' in 'where clause'", "severity": "ERROR", "timestamp": "2024-10-11T16:46:06Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "Error al eliminar pel\u00edcula: 1054 (42S22): Unknown column 'IdPeliculas' in 'where clause'", "severity": "ERROR", "timestamp": "2024-10-11T16:46:06Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "local variable 'nueva_ruta_imagen' referenced before assignment", "severity": "ERROR", "timestamp": "2024-10-11T17:05:21Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "1054 (42S22): Unknown column 'IdGenero' in 'field list'", "severity": "ERROR", "timestamp": "2024-10-21T21:33:02Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "Error al obtener el ID del g\u00e9nero: 1054 (42S22): Unknown column 'IdGenero' in 'field list'", "severity": "ERROR", "timestamp": "2024-10-21T21:33:02Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "Error al obtener el ID del g\u00e9nero: 1054 (42S22): Unknown column 'IdGenero' in 'field list'", "severity": "ERROR", "timestamp": "2024-10-21T21:33:02Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "No se encontr\u00f3 el g\u00e9nero  en la base de datos.", "severity": "ERROR", "timestamp": "2024-10-21T21:48:57Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "No se encontr\u00f3 el g\u00e9nero  en la base de datos.", "severity": "ERROR", "timestamp": "2024-10-21T21:51:00Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "'MainWindow' object has no attribute 'abrir_agregar_pelicula'", "severity": "ERROR", "timestamp": "2024-10-22T18:19:59Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "'MainWindow' object has no attribute 'usuarios_actualizados'", "severity": "ERROR", "timestamp": "2024-10-22T18:21:42Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "'MainWindow' object has no attribute 'usuarios_actualizados'", "severity": "ERROR", "timestamp": "2024-10-22T18:24:13Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "'MainWindow' object has no attribute 'usuarios_actualizados'", "severity": "ERROR", "timestamp": "2024-10-22T18:24:42Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "'ModificarPelicula' object has no attribute 'comboBox_peliculas'", "severity": "ERROR", "timestamp": "2024-10-22T20:02:02Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "'Database' object has no attribute 'obtener_datos_pelicula'", "severity": "ERROR", "timestamp": "2024-10-22T20:03:49Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "'Database' object has no attribute 'obtener_datos_pelicula'", "severity": "ERROR", "timestamp": "2024-10-22T20:04:04Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "'Database' object has no attribute 'obtener_datos_pelicula'", "severity": "ERROR", "timestamp": "2024-10-22T20:04:04Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "'Database' object has no attribute 'obtener_datos_pelicula'", "severity": "ERROR", "timestamp": "2024-10-22T20:06:47Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "'Database' object has no attribute 'obtener_datos_pelicula'", "severity": "ERROR", "timestamp": "2024-10-22T20:09:01Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "'Database' object has no attribute 'obtener_datos_pelicula'", "severity": "ERROR", "timestamp": "2024-10-22T20:11:51Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "arguments did not match any overloaded call:\n  fromString(string: Optional[str], format: Qt.DateFormat = Qt.TextDate): argument 1 has unexpected type 'datetime.date'\n  fromString(s: Optional[str], format: Optional[str]): argument 1 has unexpected type 'datetime.date'\n  fromString(s: Optional[str], format: Optional[str], cal: QCalendar): argument 1 has unexpected type 'datetime.date'", "severity": "ERROR", "timestamp": "2024-10-22T20:14:59Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "arguments did not match any overloaded call:\n  fromString(string: Optional[str], format: Qt.DateFormat = Qt.TextDate): argument 1 has unexpected type 'datetime.date'\n  fromString(s: Optional[str], format: Optional[str]): argument 1 has unexpected type 'datetime.date'\n  fromString(s: Optional[str], format: Optional[str], cal: QCalendar): argument 1 has unexpected type 'datetime.date'", "severity": "ERROR", "timestamp": "2024-10-23T10:34:05Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "arguments did not match any overloaded call:\n  fromString(string: Optional[str], format: Qt.DateFormat = Qt.TextDate): argument 1 has unexpected type 'datetime.date'\n  fromString(s: Optional[str], format: Optional[str]): argument 1 has unexpected type 'datetime.date'\n  fromString(s: Optional[str], format: Optional[str], cal: QCalendar): argument 1 has unexpected type 'datetime.date'", "severity": "ERROR", "timestamp": "2024-10-23T10:35:04Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "arguments did not match any overloaded call:\n  fromString(string: Optional[str], format: Qt.DateFormat = Qt.TextDate): argument 1 has unexpected type 'datetime.date'\n  fromString(s: Optional[str], format: Optional[str]): argument 1 has unexpected type 'datetime.date'\n  fromString(s: Optional[str], format: Optional[str], cal: QCalendar): argument 1 has unexpected type 'datetime.date'", "severity": "ERROR", "timestamp": "2024-10-23T10:35:04Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "arguments did not match any overloaded call:\n  fromString(string: Optional[str], format: Qt.DateFormat = Qt.TextDate): argument 1 has unexpected type 'datetime.date'\n  fromString(s: Optional[str], format: Optional[str]): argument 1 has unexpected type 'datetime.date'\n  fromString(s: Optional[str], format: Optional[str], cal: QCalendar): argument 1 has unexpected type 'datetime.date'", "severity": "ERROR", "timestamp": "2024-10-23T10:41:09Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "isinstance() arg 2 must be a type or tuple of types", "severity": "ERROR", "timestamp": "2024-10-23T10:44:35Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "isinstance() arg 2 must be a type or tuple of types", "severity": "ERROR", "timestamp": "2024-10-23T10:56:16Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "'Database' object has no attribute 'obtener_generos_pelicula'", "severity": "ERROR", "timestamp": "2024-10-23T11:01:08Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "type object 'datetime.datetime' has no attribute 'datetime'", "severity": "ERROR", "timestamp": "2024-10-23T11:05:14Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "type object 'datetime.datetime' has no attribute 'datetime'", "severity": "ERROR", "timestamp": "2024-10-23T11:06:11Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "type object 'datetime.datetime' has no attribute 'datetime'", "severity": "ERROR", "timestamp": "2024-10-23T11:07:36Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "'Database' object has no attribute 'obtener_generos_pelicula'", "severity": "ERROR", "timestamp": "2024-10-23T11:10:21Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "'ModificarPelicula' object has no attribute 'dateEdit_inicio'", "severity": "ERROR", "timestamp": "2024-10-23T11:11:14Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "'Database' object has no attribute 'obtener_generos_pelicula'", "severity": "ERROR", "timestamp": "2024-10-23T11:16:09Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "'Database' object has no attribute 'obtener_generos_pelicula'", "severity": "ERROR", "timestamp": "2024-10-23T11:19:50Z"}
